---
extends: default

rules:
  line-length:
    max: 120
    level: warning
  document-start: disable
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
