apiVersion: v1
kind: Secret
metadata:
  name: xperience-db-credentials
  namespace: apps
type: Opaque
stringData:
  url: "postgresql://postgres:SuperSecretPassword123@postgresql-dev.database.svc.cluster.local:5432/xperience_prod"
