apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: postgresql
    targetRevision: '15.5.4'
    helm:
      values: |
        global:
          postgresql:
            auth:
              database: n8n
              username: postgres
              existingSecret: postgresql-dev-credentials
              secretKeys:
                adminPasswordKey: postgres-password
        primary:
          persistence:
            enabled: true
            size: 8Gi
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1024Mi
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
